### ISSUE TITLE
Fatal Error when visiting cart page.

### ISSUE THREAD

**Issue by kartikparmar** [TycheSoftwares/Multiple-Time-Slot-addon#51]
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (2020-10-21&lt;br&gt;09:00 AM) at position 10 (&lt;): Unexpected character in C:\xampp\htdocs\rental\wp-content\plugins\woocommerce-booking\includes\bkap-validation.php:1722 Stack trace: #0 C:\xampp\htdocs\rental\wp-content\plugins\woocommerce-booking\includes\bkap-validation.php(1722): DateTime->__construct('2020-10-21<br>0...') #1 C:\xampp\htdocs\rental\wp-includes\class-wp-hook.php(287): bkap_validation::bkap_remove_product_from_cart('') #2 C:\xampp\htdocs\rental\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\rental\wp-includes\plugin.php(478): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\rental\wp-content\plugins\woocommerce\includes\shortcodes\class-wc-shortcode-cart.php(91): do_action('woocommerce_che...') #5 C:\xampp\htdocs\rental\wp-content\plugins\woocommerce\includes\class-wc-shortcodes.php(72): WC_Shortcode_Cart::output(Array) #6 C:\xampp\htdocs\rental\wp-content\plugins\woocommerce\ in C:\xampp\htdocs\rental\wp-content\plugins\woocommerce-booking\includes\bkap-validation.php on line 1722

Product Type : Simple
Booking Type: Fixed Time
Timeslots: 09:00 - 10:00, 10:00 - 11:00 for all weekdays

On front end, selected the booking date and time and added to the cart. All good.
Visited the Cart page and it throws the above fatal error.

**Comment by kartikparmar** [comment]
Fixed in https://github.com/TycheSoftwares/woocommerce-booking/pull/4006/commits/6a0239c8bb1aa48250e4e4bb984521cbb737c9c0 commit hence closing it.
